apiVersion: apps/v1
kind: Deployment
metadata:
  name: tankyoutext
  labels:
    app: tankyoutext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tankyoutext
  template:
    metadata:
      labels:
        app: tankyoutext
    spec:
      containers:
        - name: tankyoutext
          image: username/tankyoutext:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
