server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, 
        - id: pay
          uri: http://localhost:8082
          predicates:
            - Path=/payments/**, 
        - id: tankyoutext
          uri: http://localhost:8083
          predicates:
            - Path=/tankytexts/**, 
        - id: store
          uri: http://localhost:8084
          predicates:
            - Path=/foodCookings/**, 
        - id: customer
          uri: http://localhost:8085
          predicates:
            - Path=, /orderinfos/**
        - id: rider
          uri: http://localhost:8086
          predicates:
            - Path=/deliveries/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://front:8080
          predicates:
            - Path=/orders/**, 
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/payments/**, 
        - id: tankyoutext
          uri: http://tankyoutext:8080
          predicates:
            - Path=/tankytexts/**, 
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/foodCookings/**, 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=, /orderinfos/**
        - id: rider
          uri: http://rider:8080
          predicates:
            - Path=/deliveries/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
